name: Update filters

on:
  push:
    branches:
      - master
  schedule:
    # Every Monday at 08:00 AM
    - cron:  '0 8 * * 1'

permissions:
  pull-requests: write

jobs:
  check:
    name: Check filters update
    runs-on: ubuntu-latest
    outputs:
      need_update: ${{ steps.diff.outputs.results }}
    steps:
      - name: Setup dependencies
        run: sudo apt-get -y install cabextract

      - uses: actions/checkout@v2

      - name: Update filters
        run: bash update.sh

      - name: git diff and set output
        id: diff
        run: |
          # Ignore diff exit code
          set +e
          git diff --exit-code --quiet
          echo "results=$?" >> $GITHUB_OUTPUT

  update:
    runs-on: ubuntu-latest
    name: Commit filters update
    needs: [ check ]
    if: needs.check.outputs.need_update == 1
    steps:
      - name: Setup dependencies
        run: sudo apt-get -y install cabextract

      - uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Update filters
        run:
          git checkout -B "${SOURCE_BRANCH}"
          bash update.sh
          git add .
          git commit -m "${COMMIT_TITLE}"
          gh pr create --title "${COMMIT_TITLE}" --base "${DEST_BRANCH}" --head "${SOURCE_BRANCH}"
        env:
          SOURCE_BRANCH: bump-${{ steps.date.outputs.date }}
          DEST_BRANCH: master
          COMMIT_TITLE: 'Update filters (${{ steps.date.outputs.date }})'
          github_token: ${{ secrets.GITHUB_TOKEN }}
